export const disciplinas = [
  { id: 1, nome: "Análise e Projeto de Sistemas" },
  { id: 2, nome: "Análise e Projeto de Sistemas II" },
  { id: 3, nome: "Ciência de Dados e Aprendizagem de Máquina" },
  { id: 4, nome: "Computação Gráfica" },
  { id: 5, nome: "Engenharia de Software" },
  { id: 6, nome: "Estruturas de Dados I" },
  { id: 7, nome: "Estruturas de Dados II" },
  { id: 8, nome: "Fundamentos de Inteligência Artificial" },
  { id: 9, nome: "Gestão de Projeto em Sistemas de Informação" },
  { id: 10, nome: "Gestão de Sistemas de Informação e Métodos" },
  { id: 11, nome: "Laboratório de Banco de Dados" },
  { id: 12, nome: "Paradigmas de Linguagens de Programação" },
  { id: 13, nome: "Programação Para Dispositivos Móveis" },
  { id: 14, nome: "Programação Web" },
  { id: 15, nome: "Projeto de Linguagens de Programação" },
  { id: 16, nome: "Redes de Computadores" },
  { id: 17, nome: "Segurança e Auditoria de Sistemas" },
  { id: 18, nome: "Sistemas Operacionais" },
  { id: 19, nome: "Técnicas de Desenvolvimento de Algoritmos" },
  { id: 20, nome: "Técnicas de Programação" },
  { id: 21, nome: "Teoria Geral da Administração" },
  { id: 22, nome: "Analise de Dados" },
  { id: 23, nome: "Computabilidade e Complexibilidade de Algoritmos" },
];
